# インストール可能なrubyバージョン一覧
# mise ls-remote ruby
#
# 不要なバージョン等を削除
# mise prune
#
# 利用できるプラグイン一覧
# mise plugins update
# mise plugins ls-remote
#
[tools]
# mise ls-remote --all
# mise ls-remote go
go = ['1.25.3']
ruby = ['3.4.2']
nodejs = ['24.1.0']
java = ['temurin-21.0.5+11.0.LTS']
opentofu = ['1.9.0']
terraform = "1.14.1"
python = ['3.12']
zig = ['0.15.2']
bun = 'latest'
deno = 'latest'

# awscli: 別のCPU typeがインストールされるので、brewで管理
# awscli = ['2.21.2', '2.21.3']
# mise outdated で確認
aws-vault = 'latest'
tmux = '3.5a'
jq = 'latest'
alp = 'latest'
ripgrep = 'latest'
delta = 'latest'
lazygit = 'latest'
lsd = 'latest'
eza = 'latest'
yq = 'latest'
gh = 'latest'
direnv = 'latest'
poetry = 'latest'
typst = 'latest'
grpcurl = 'latest'
protoc = 'latest'
eksctl = '0.220.0'
kubectl = '1.34.3'

[settings]
# idiomatic version fileを有効化するかどうか
# asdfやmiseなどのバージョン管理ツールに依存しない「言語毎に標準的なバージョンファイル」
# 例: .go-version
idiomatic_version_file_enable_tools = ["go"]
